---
language: ruby
rvm:
- 2.0.0
before_script: bundle exec rake hatchet:setup_travis
script: bundle exec parallel_test test/hatchet -n 6
after_script: bundle exec rake hatchet:teardown_travis

env:
  global:
  - HATCHET_RETRIES=3
  - secure: |-
      SfUgPagZILPjm4rjkYlEck76PUE47dimpNZgUtUf7wTAbe6EE83QmnRl6uDT
      eSdxuY9uNFoTwNLC0J+mRiDAJtAQxBsst8wFoc3diK2o8Ojnor5yd3cxddBv
      uvJK6optVPzDveg7rjC7zsELzWYvzWW9enZ6gr8BY/cIPIWTXMw=
